### ISSUE TITLE
Docker reporting error (Can't find mounted cgroups)

### ISSUE THREAD

**Issue by cementito** [tutumcloud/datadog-agent#1]
After deploying the container on two nodes with Tutum's Jumpstart, I only get partial reporting.
ntp and system metrics are reported properly, but not docker specific metrics.

In DataDog's interface, the following error is reported:

    Instance #initialization[ERROR]:Exception("Can't find mounted cgroups. If you run the Agent inside a container, please refer to the documentation.",)

![image](https://cloud.githubusercontent.com/assets/1539620/9624661/2859a7c2-514f-11e5-89d5-4372c19cb4ad.png)

**Comment by fermayo** [comment]
Which distro are you using? Or is it a tutum-deployed node?

**Comment by cementito** [comment]
It's a tutum-deployed node on DigitalOcean/AMS2/1Gb (same behaviour on the two nodes I tried to deploy to).
.

**Comment by cementito** [comment]
Found out that the Jumpstart installation via Tutum didn't create the required volume mappings.
Installed according to https://stackfiles.io and now docker stats are reported properly.

Documentation should probably hint to this.

volumes:
"/var/run/docker.sock:/var/run/docker.sock"
"/proc/mounts:/host/proc/mounts:ro"
"/sys/fs/cgroup:/host/sys/fs/cgroup:ro"

**Comment by fermayo** [comment]
We are working to make this work OOTB in Tutum when you select the jumpstart in the new service wizard. Sorry for the confusion and thanks for letting us know.
